#!/bin/bash

# Import the Primmer trimmed (using cutadapt) sequences into QIIME2
qiime tools import --type SampleData[PairedEndSequencesWithQuality] --input-path FUT2_QIIME2_manifest_V1V3Samples.txt --output-path ./V1V3_Processing/FUT2-PTrimV1V3.qza --input-format PairedEndFastqManifestPhred33V2

qiime demux summarize --i-data ./V1V3_Processing/FUT2-PTrimV1V3.qza --o-visualization ./V1V3_Processing/FUT2-PTrimV1V3.qzv

# DADA2 denoising using only forward read
qiime dada2 denoise-single --i-demultiplexed-seqs ./V1V3_Processing/FUT2-PTrimV1V3.qza  --p-n-threads 10 --p-max-ee 5 --p-trunc-q 10 --p-trunc-len 0 --o-representative-sequences ./V1V3_Processing/FUT2-PTrimV1V3-rep-seqs-dada2.qza --o-table ./V1V3_Processing/FUT2-PTrimV1V3-table-dada2.qza --o-denoising-stats ./V1V3_Processing/FUT2-PTrimV1V3-stats-dada2.qza

# Generate dada2 stats
qiime metadata tabulate --m-input-file  ./V1V3_Processing/FUT2-PTrimV1V3-stats-dada2.qza --o-visualization  ./V1V3_Processing/FUT2-PTrimV1V3-stats-dada2.qzv

# Generate dada2 counts
qiime feature-table summarize --i-table ./V1V3_Processing/FUT2-PTrimV1V3-table-dada2.qza --o-visualization ./V1V3_Processing/FUT2-PTrimV1V3-table-dada2.qzv

# Generate dada 2 ASV seqs
qiime feature-table tabulate-seqs --i-data ./V1V3_Processing/FUT2-PTrimV1V3-rep-seqs-dada2.qza  --o-visualization ./V1V3_Processing/FUT2-PTrimV1V3-rep-seqs-dada2.qzv


# Classify taxonomy using the SILVA Naive Bayes
qiime feature-classifier classify-sklearn --i-classifier ./qiime2-classifiers/silva-138.1-ssu-nr99-seqs-V1V3_forwardCustom-classifier.qza --i-reads ./V1V3_Processing/FUT2-PTrimV1V3-rep-seqs-dada2.qza --o-classification ./V1V3_Processing/FUT2-PTrimV1V3-SILVA-Taxonomy.qza

qiime metadata tabulate --m-input-file ./V1V3_Processing/FUT2-PTrimV1V3-SILVA-Taxonomy.qza --o-visualization ./V1V3_Processing/FUT2-PTrimV1V3-SILVA-Taxonomy.qzv

qiime krona collapse-and-plot --i-table ./V1V3_Processing/FUT2-PTrimV1V3-table-dada2.qza --i-taxonomy ./V1V3_Processing/FUT2-PTrimV1V3-SILVA-Taxonomy.qza --o-krona-plot ./V1V3_Processing/FUT2-PTrimV1V3-SILVA-Taxonomy.qzv


qiime tools export --input-path ./V1V3_Processing/FUT2-PTrimV1V3-table-dada2.qza --output-path ./V1V3_Processing/FUT2-ASV-Outputs-SILVA/

biom convert -i ./V1V3_Processing/FUT2-ASV-Outputs-SILVA/feature-table.biom -o ./V1V3_Processing/FUT2-ASV-Outputs-SILVA/table.tsv --to-tsv


# Export Species level
qiime taxa collapse --i-table ./V1V3_Processing/FUT2-PTrimV1V3-table-dada2.qza --i-taxonomy ./V1V3_Processing/FUT2-PTrimV1V3-SILVA-Taxonomy.qza --p-level 7 --o-collapsed-table ./V1V3_Processing/FUT2-PTrimV1V3-table-species.qza

qiime tools export --input-path  ./V1V3_Processing/FUT2-PTrimV1V3-table-species.qza --output-path ./V1V3_Processing/FUT2-ASV-Outputs-SILVA/Species/

biom convert -i ./V1V3_Processing/FUT2-ASV-Outputs-SILVA/Species/feature-table.biom -o ./V1V3_Processing/FUT2-ASV-Outputs-SILVA/Species/table.tsv --to-tsv


# Export Genera level
qiime taxa collapse --i-table ./V1V3_Processing/FUT2-PTrimV1V3-table-dada2.qza --i-taxonomy ./V1V3_Processing/FUT2-PTrimV1V3-SILVA-Taxonomy.qza --p-level 6 --o-collapsed-table ./V1V3_Processing/FUT2-PTrimV1V3-table-genera.qza

qiime tools export --input-path ./V1V3_Processing/FUT2-PTrimV1V3-table-genera.qza --output-path ./V1V3_Processing/FUT2-ASV-Outputs-SILVA/Genera/

biom convert -i ./V1V3_Processing/FUT2-ASV-Outputs-SILVA/Genera/feature-table.biom -o ./V1V3_Processing/FUT2-ASV-Outputs-SILVA/Genera/table.tsv --to-tsv


# Valencia
python convert_qiime.py -i ./V1V3_Processing/FUT2-ASV-Outputs-SILVA/table.tsv -t ./V1V3_Processing/FUT2-ASV-Outputs-SILVA/taxonomy.tsv --ref ./CST_centroids_012920.csv

python Valencia.py -i ./taxon_table_asv_merged.csv -r ./CST_centroids_012920.csv -p ./VALENCIA_V1V3 -o ./VALENCIA_V1V3


